#HeaderRevision 0
#
# File generated by...
# program:      StateDMI 3.12.02 (2013-04-17)
# user:         CTS
# date:         Mon Jul 11 11:13:49 MDT 2016
# host:         Logan_Laptop
# directory:    C:\Users\CTS\Google Drive\CDSS\Data\cm2015_7\Reservoirs
# command line: StateDMI
#
#----
# -----------------------------------------------------------------------
# Command file name: "C:\Users\CTS\Google Drive\CDSS\Data\cm2015_7\Reservoirs\Bres.commands.StateDMI"
# Commands:
# # Bres.commands.StateDMI
# #  Only differs from res.command file in regards to the 10825 fish accounts.
# #
# # Creates the reservoir station file for the Upper Colorado River monthly models
# # Initial reservoir contents are set to 9/1908 estimated contents
# #
# # Phase IIIb modifications
# #	to reflect reservoir storage as of October 1908 - zero out account owners' current
# #	storage capacity if the reservoir came on-line during the study period.
# #	No changes made to reservoirs that were on-line in 10/1908 (including aggregate storage).
# #
# #	Turned on Wolford Mountain and added Wolford Mountain accounts and storage rights per CWCB
# #
# #       Treat Vega with one pool only - power releases first, then irrigation releases.
# #       to the Power Exchange pool, and could not get released for use
# #
# # commands used in this file establish reservoir capacity, fill date,
# # reservoir account ownership, area-capacity tables and representative
# # evaporation stations (see StateMod documentation)
# #
# #
# #  Step 1 - read reservoirs from network file and sort alphabetically
# #
# ReadReservoirStationsFromNetwork(InputFile="..\network\cm2015.net")
# SortReservoirStations(Order=Ascending)
# #
# #  Step 2 - read reservoir information from HydroBase
# #
# FillReservoirStationsFromHydroBase(ID="*")
# #
# #  Step 3 - set reservoir information not available in HydroBase including min/max
# #           content, starting content, and account information
# #
# # GREEN MOUNTAIN RESERVIOR Characteristics
# SetReservoirStation(ID="3603543",Name="GREEN MTN RES",OnOff=3,OneFillRule=4,DailyID="5",ContentMin=0,ContentMax=154645,ReleaseMax=4010,DeadStorage=0,AccountID=1,AccountName="Hist_Users",AccountMax=66000,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10008,100",IfNotFound=Warn)
# SetReservoirStation(ID="3603543",AccountID=2,AccountName="CBT_Pool",AccountMax=52000,AccountInitial=48095,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="3603543",AccountID=3,AccountName="Contract",AccountMax=20000,AccountInitial=19453,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="3603543",AccountID=4,AccountName="Silt_Proj",AccountMax=5000,AccountInitial=4952,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="3603543",AccountID=5,AccountName="Inactive",AccountMax=11645,AccountInitial=10537,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="3603543",AccountID=6,AccountName="SurplusFish",AccountMax=66000,AccountInitial=0,AccountEvap=0,IfNotFound=Warn)
# #
# # UPPER BLUE RESERVOIR Characteristics (Task Order LR-2 enhancement)
# SetReservoirStation(ID="3603570",Name="CONT_HOOSIER_BLUE_RES",OnOff=1,OneFillRule=4,DailyID="5",ContentMin=0,ContentMax=2113,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Active",AccountMax=2140,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10008,100",ContentAreaSeepage="0,0,0;2140,214.0,0;9999999,214.0,0",IfNotFound=Warn)
# SetReservoirStation(ID="3603570",AccountID=2,AccountName="CSprings-OOP",AccountMax=2100,AccountInitial=1850,AccountEvap=0,IfNotFound=Add)
# SetReservoirStation(ID="3603570",AccountID=3,AccountName="MOA_Rel",AccountMax=250,AccountInitial=250,AccountEvap=-1,IfNotFound=Add)
# #
# # CLINTON GULCH RESERVOIR  Characteristics
# SetReservoirStation(ID="3603575",OnOff=1,OneFillRule=4,DailyID="5",ContentMin=0,ContentMax=4300,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Breck-Town",AccountMax=390,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10008,100",IfNotFound=Warn)
# SetReservoirStation(ID="3603575",AccountID=2,AccountName="Dillon-Town",AccountMax=60,AccountInitial=52,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="3603575",AccountID=3,AccountName="Silverthorne",AccountMax=165,AccountInitial=142,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="3603575",AccountID=4,AccountName="Breck-Ski",AccountMax=455,AccountInitial=392,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="3603575",AccountID=5,AccountName="Copper_Mtn",AccountMax=490,AccountInitial=422,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="3603575",AccountID=6,AccountName="Keystone",AccountMax=1305,AccountInitial=1305,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="3603575",AccountID=7,AccountName="Winter_Park",AccountMax=270,AccountInitial=233,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="3603575",AccountID=8,AccountName="Summit_Co.",AccountMax=465,AccountInitial=401,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="3603575",AccountID=9,AccountName="Dead_Pool",AccountMax=700,AccountInitial=601,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# #
# # DILLON RESERVOIR  Characteristics
# SetReservoirStation(ID="3604512",OnOff=1,OneFillRule=4,DailyID="5",ContentMin=0,ContentMax=257000,ReleaseMax=1940,DeadStorage=0,AccountID=1,AccountName="Denver/RT",AccountMax=252015,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10008,100",IfNotFound=Warn)
# SetReservoirStation(ID="3604512",AccountID=2,AccountName="Summit_Co.",AccountMax=1021,AccountInitial=728,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="3604512",AccountID=3,AccountName="Dead_Pool",AccountMax=3269,AccountInitial=2332,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="3604512",AccountID=4,AccountName="1000_acft",AccountMax=1000,AccountInitial=157,AccountEvap=0,IfNotFound=Warn)
# SetReservoirStation(ID="3604512",AccountID=5,AccountName="Denver-OOP1",AccountMax=154645,AccountInitial=2228,AccountEvap=0,IfNotFound=Warn)
# #
# # District 36 Aggregated Reservoirs - include 10 aggregated reservoirs
# SetReservoirStation(ID="36_ARC001",Name="36_ARC001",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=8702,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="36_ARC001",AccountMax=8702,AccountInitial=8702,AccountEvap=0,AccountOneFill=1,EvapStations="10008,100",ContentAreaSeepage="0,0,0;8702,348.08,0;9999999,348.08,0",IfNotFound=Warn)
# #
# # WOLCOTT RESERVOIR Characteristics
# SetReservoirStation(ID="3703639",OnOff=0,OneFillRule=4,DailyID="5",ContentMin=0,ContentMax=65975,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Active",AccountMax=65975,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10006,100",ContentAreaSeepage="0,0,0;65975,6597,0;99999,6597,0",IfNotFound=Warn)
# #
# # EAGLE PARK RESERVOIR Characteristics
# SetReservoirStation(ID="3703699",Name="EAGLE PARK",OnOff=0,OneFillRule=4,DailyID="5",ContentMin=0,ContentMax=3148,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Eagle_R_W&S",AccountMax=330,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10008,100",ContentAreaSeepage="0,0,0;3148,315,0;9999,315,0",IfNotFound=Warn)
# SetReservoirStation(ID="3703699",AccountID=2,AccountName="UERRWA",AccountMax=383,AccountInitial=0,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="3703699",AccountID=3,AccountName="Vail_Valley",AccountMax=1100,AccountInitial=0,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="3703699",AccountID=4,AccountName="River_Dist",AccountMax=200,AccountInitial=0,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# #
# # HOMESTAKE PROJ RESERVOIR Characteristics
# SetReservoirStation(ID="3704516",OnOff=1,OneFillRule=4,DailyID="5",ContentMin=0,ContentMax=43600,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="CS_&_Aurora",AccountMax=42881,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10006,100",IfNotFound=Warn)
# SetReservoirStation(ID="3704516",AccountID=2,AccountName="Dead_Pool",AccountMax=211,AccountInitial=205,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="3704516",AccountID=3,AccountName="HR_GMR",AccountMax=21440,AccountInitial=0,AccountEvap=0,IfNotFound=Warn)
# #
# # District 37 Aggregated Reservoirs
# SetReservoirStation(ID="37_ARC002",Name="37_ARC002",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=6671,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="37_ARC002",AccountMax=6671,AccountInitial=6671,AccountEvap=0,AccountOneFill=1,EvapStations="10006,100",ContentAreaSeepage="0,0,0;6671,266.84,0;9999999,266.84,0",IfNotFound=Warn)
# #
# # RUEDI RESERVOIR Characteristics
# SetReservoirStation(ID="3803713",Name="RUEDI_RESERVOIR",OnOff=1,OneFillRule=4,DailyID="5",ContentMin=0,ContentMax=102373,ReleaseMax=1390,DeadStorage=0,AccountID=1,AccountName="Rnd_1&2_Cont",AccountMax=30263,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10006,100",IfNotFound=Warn)
# SetReservoirStation(ID="3803713",AccountID=2,AccountName="Replacement",AccountMax=28000,AccountInitial=26575,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="3803713",AccountID=3,AccountName="Unalloc/Dead",AccountMax=28698,AccountInitial=21713,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="3803713",AccountID=4,AccountName="CWCB_Fish",AccountMax=5413,AccountInitial=5142,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="3803713",AccountID=5,AccountName="Unalloc/5k",AccountMax=5000,AccountInitial=0,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="3803713",AccountID=6,AccountName="USFWS_5k_4/5",AccountMax=5000,AccountInitial=0,AccountEvap=0,IfNotFound=Warn)
# #
# # District 38 Aggregated Reservoirs
# SetReservoirStation(ID="38_ARC003",Name="38_ARC003",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=13074,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="38_ARC003",AccountMax=13074,AccountInitial=13074,AccountEvap=0,AccountOneFill=1,EvapStations="10006,100",ContentAreaSeepage="0,0,0;13074,522.9,0;9999999,522.9,0",IfNotFound=Warn)
# #
# # GRASS VALLEY RESERVOIR  Characteristics
# SetReservoirStation(ID="3903505",OnOff=1,OneFillRule=11,DailyID="5",ContentMin=0,ContentMax=5920,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Farmers",AccountMax=5920,AccountInitial=2233,AccountEvap=0,AccountOneFill=1,EvapStations="10005,100",IfNotFound=Warn)
# #
# # RIFLE GAP RESERVOIR   Characteristics
# SetReservoirStation(ID="3903508",OnOff=1,OneFillRule=11,DailyID="5",ContentMin=0,ContentMax=13602,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Silt_Pool",AccountMax=12168,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10005,100",IfNotFound=Warn)
# SetReservoirStation(ID="3903508",AccountID=2,AccountName="Dead_Pool",AccountMax=1434,AccountInitial=1382,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# #
# # RIFLE GAP EXCHANGE RESERVOIR   Characteristics
# SetReservoirStation(ID="3903508_Ex",OnOff=1,OneFillRule=11,DailyID="5",ContentMin=0,ContentMax=999999,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Exchange",AccountMax=999999,AccountInitial=0,AccountEvap=-1,AccountOneFill=1,ContentAreaSeepage="0,0,0;999999,99999,0",IfNotFound=Warn)
# #
# # District 39 Aggregated Reservoirs
# SetReservoirStation(ID="39_ARC004",Name="39_ARC004",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=2236,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="39_ARC004",AccountMax=2236,AccountInitial=2236,AccountEvap=0,AccountOneFill=1,EvapStations="10005,100",ContentAreaSeepage="0,0,0;2236,89.4,0;9999999,89.4,0",IfNotFound=Warn)
# #
# # District 45 Aggregated Reservoirs
# SetReservoirStation(ID="45_ARC005",Name="45_ARC005",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=2054,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="45_ARC005",AccountMax=2054,AccountInitial=2054,AccountEvap=0,AccountOneFill=1,EvapStations="10005,100",ContentAreaSeepage="0,0,0;2054,82.2,0;9999999,82.2,0",IfNotFound=Warn)
# #
# # WOLFORD MOUNTAIN RES Characteristics
# SetReservoirStation(ID="5003668",Name="WOLFORD_MOUNTAIN_RES",OnOff=1,OneFillRule=4,DailyID="5",ContentMin=0,ContentMax=65985,ReleaseMax=992,DeadStorage=0,AccountID=1,AccountName="West_Slope",AccountMax=39796,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10008,100",ContentAreaSeepage="0,0,0;23206,753,0;27112,810,0;31307,869,0;35910,973,0;41051,1084,0;46761,1201,0;52069,1323,0;59993,1447,0;65985,1550,0;9999999,1550,0",IfNotFound=Warn)
# SetReservoirStation(ID="5003668",AccountID=2,AccountName="Denver",AccountMax=25610,AccountInitial=25035,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="5003668",AccountID=3,AccountName="Fish_Account1",AccountMax=3000,AccountInitial=2670,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="5003668",AccountID=4,AccountName="Fish_Account2",AccountMax=3000,AccountInitial=2670,AccountEvap=0,IfNotFound=Warn)
# SetReservoirStation(ID="5003668",AccountID=5,AccountName="Denver_R1",AccountMax=5000,AccountInitial=0,AccountEvap=0,IfNotFound=Warn)
# SetReservoirStation(ID="5003668",AccountID=6,AccountName="Denver_R2",AccountMax=20610,AccountInitial=0,AccountEvap=0,IfNotFound=Warn)
# SetReservoirStation(ID="5003668",AccountID=7,AccountName="C.Springs",AccountMax=1750,AccountInitial=875,AccountEvap=0,IfNotFound=Warn)
# SetReservoirStation(ID="5003668",AccountID=8,AccountName="C.Springs_B",AccountMax=250,AccountInitial=0,AccountEvap=0,IfNotFound=Warn)
# SetReservoirStation(ID="5003668",AccountID=9,AccountName="C.Springs_R",AccountMax=1750,AccountInitial=0,AccountEvap=0,IfNotFound=Warn)
# #
# # District 50 Aggregated Reservoirs
# SetReservoirStation(ID="50_ARC006",Name="50_ARC006",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=11481,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="50_ARC006",AccountMax=11481,AccountInitial=11481,AccountEvap=0,AccountOneFill=1,EvapStations="10008,100",ContentAreaSeepage="0,0,0;11481,459.2,0;9999999,459.2,0",IfNotFound=Warn)
# #
# # MEADOW CREEK RESERVOIR Characteristics
# SetReservoirStation(ID="5103686",OnOff=1,OneFillRule=4,DailyID="5",ContentMin=0,ContentMax=5930,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Denver/Engl",AccountMax=4780,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10009,100",IfNotFound=Warn)
# SetReservoirStation(ID="5103686",AccountID=2,AccountName="VailDitch",AccountMax=850,AccountInitial=819,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="5103686",AccountID=3,AccountName="Dead_Pool",AccountMax=300,AccountInitial=292,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# #
# # SHADOW MOUNTAIN/GRAND LAKE Characteristics
# SetReservoirStation(ID="5103695",OnOff=1,OneFillRule=4,DailyID="5",ContentMin=0,ContentMax=18369,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Account",AccountMax=1839,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10009,100",IfNotFound=Warn)
# SetReservoirStation(ID="5103695",AccountID=2,AccountName="Dead_Pool",AccountMax=16530,AccountInitial=16397,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# #
# # WILLIAMS FORK RESERVOIR Characteristics
# SetReservoirStation(ID="5103709",OnOff=1,OneFillRule=4,DailyID="5",ContentMin=0,ContentMax=96822,ReleaseMax=1860,DeadStorage=0,AccountID=1,AccountName="Denver",AccountMax=99765,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10008,100",IfNotFound=Warn)
# SetReservoirStation(ID="5103709",AccountID=2,AccountName="Henderson",AccountMax=2200,AccountInitial=1723,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="5103709",AccountID=3,AccountName="WF_Fish_Temp",AccountMax=0,AccountInitial=0,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="5103709",AccountID=4,AccountName="WF_GMR1",AccountMax=10000,AccountInitial=0,AccountEvap=0,IfNotFound=Warn)
# SetReservoirStation(ID="5103709",AccountID=5,AccountName="WF_GMR2",AccountMax=25000,AccountInitial=0,AccountEvap=0,IfNotFound=Warn)
# #
# # CBT WILLOW CREEK RES Characteristics
# SetReservoirStation(ID="5103710",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=10553,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="CBT_Pool",AccountMax=3329,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10009,100",IfNotFound=Warn)
# SetReservoirStation(ID="5103710",AccountID=2,AccountName="Dead_Pool",AccountMax=7224,AccountInitial=6123,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# #
# # CBT GRANBY RESERVOIR  Characteristics
# SetReservoirStation(ID="5104055",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=539758,ReleaseMax=2460,DeadStorage=0,AccountID=1,AccountName="CBT_Pool",AccountMax=465568,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10009,100",ContentAreaSeepage="0.00,0.00,0;109,22.00,0;1406,115,0;5175,259,0;11792,403,0;23661,869,0;53574,2061,0;105132,3117,0;178168,4165,0;271459,5182,0;385040,6155,0;483058,6943,0;539758,7256,0;9999999,7256,0",IfNotFound=Warn)
# SetReservoirStation(ID="5104055",AccountID=2,AccountName="Dead_Pool",AccountMax=74190,AccountInitial=72670,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="5104055",AccountID=3,AccountName="Fish_Account",AccountMax=5413,AccountInitial=0,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# #
# # District 51 Aggregated Reservoirs
# SetReservoirStation(ID="51_ARC007",Name="51_ARC007",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=8480,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="51_ARC007",AccountMax=8480,AccountInitial=8480,AccountEvap=0,AccountOneFill=1,EvapStations="10009,100",ContentAreaSeepage="0,0,0;8480,339.2,0;9999999,339.2,0",IfNotFound=Warn)
# #
# # District 52 Aggregated Reservoirs
# SetReservoirStation(ID="52_ARC008",Name="52_ARC008",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=821,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="52_ARC008",AccountMax=821,AccountInitial=821,AccountEvap=0,AccountOneFill=1,EvapStations="10006,100",ContentAreaSeepage="0,0,0;821,32.8,0;9999999,32.8,0",IfNotFound=Warn)
# #
# # District 53 Aggregated Reservoirs
# SetReservoirStation(ID="53_ARC009",Name="53_ARC009",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=8389,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="53_ARC009",AccountMax=8389,AccountInitial=8389,AccountEvap=0,AccountOneFill=1,EvapStations="10006,100",ContentAreaSeepage="0,0,0;8389,335.6,0;9999999,335.6,0",IfNotFound=Warn)
# #
# # LEON CREEK AGGRES RES Characteristics
# SetReservoirStation(ID="7203839",Name="LEON_LAKEAGG_RES",OnOff=1,OneFillRule=4,DailyID="5",ContentMin=0,ContentMax=2904,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Active",AccountMax=2904,AccountInitial=1500,AccountEvap=0,AccountOneFill=1,EvapStations="10006,100",ContentAreaSeepage="0,0,0;2904,200,0;9999999,200,0",IfNotFound=Warn)
# SetReservoirStation(ID="7203842",Name="MONUMENTAGG_RES",OnOff=1,OneFillRule=4,DailyID="5",ContentMin=0,ContentMax=987,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Active",AccountMax=987,AccountInitial=500,AccountEvap=0,AccountOneFill=1,EvapStations="10006,100",ContentAreaSeepage="0,0,0;987,90,0;9999999,90,0",IfNotFound=Warn)
# #
# # VEGA RESERVOIR Characteristics
# SetReservoirStation(ID="7203844",OnOff=1,OneFillRule=11,DailyID="5",ContentMin=0,ContentMax=34131,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Project_Irr",AccountMax=33311,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10006,100",IfNotFound=Warn)
# SetReservoirStation(ID="7203844",AccountID=2,AccountName="Dead_Pool",AccountMax=820,AccountInitial=672,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# #
# # JERRY CREEK RESERVOIRS Characteristics
# SetReservoirStation(ID="7203961",Name="JERRY_CREEK_RES",OnOff=1,OneFillRule=4,DailyID="5",ContentMin=0,ContentMax=8623,ReleaseMax=999999,DeadStorage=163,AccountID=1,AccountName="Active",AccountMax=8460,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10006,100",ContentAreaSeepage="0,0,0;1000,46.0,0;3000,108,0;4000,133,0;5000,151,0;8500,180,0",IfNotFound=Warn)
# #
# # District 72 Aggregated Reservoirs
# SetReservoirStation(ID="72_ARC010",Name="72_ARC010",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=25664,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="72_ARC010",AccountMax=25664,AccountInitial=25664,AccountEvap=0,AccountOneFill=1,EvapStations="10006,100",ContentAreaSeepage="0,0,0;25664,1026.6,0;9999999,1026.6,0",IfNotFound=Warn)
# #
# # District 72 Aggregated Stock Ponds
# SetReservoirStation(ID="72_ASC001",Name="72_ASC001",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=2261,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="72_ASC001",AccountMax=2261,AccountInitial=2261,AccountEvap=0,AccountOneFill=1,EvapStations="10006,100",ContentAreaSeepage="0,0,0;2261,226.1,0;9999999,226.1,0",IfNotFound=Warn)
# #
# #  BONHAM AGGREGATED RES   Characteristics
# SetReservoirStation(ID="7203904AG",Name="BONHAMAGGREGATED_RES",OnOff=1,OneFillRule=4,DailyID="5",ContentMin=0,ContentMax=6778,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Active",AccountMax=6778,AccountInitial=6778,AccountEvap=0,AccountOneFill=1,EvapStations="10006,100",ContentAreaSeepage="0,0,0;0,0,0;1000,46,0;1500,60,0;2222,76,0;2500,96,0;3000,108,0;3500,121,0;4000,133,0;4500,143,0;5000,151,0;5500,161,0;6000,169,0;6500,177,0;7000,178,0;9999999,178,0",IfNotFound=Warn)
# #
# # COTTONWOOD AGGREG RES Characteristics
# SetReservoirStation(ID="7204033AG",Name="COTTONWOODAGGREG_RES",OnOff=1,OneFillRule=4,DailyID="5",ContentMin=0,ContentMax=3812,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Active",AccountMax=3812,AccountInitial=3812,AccountEvap=0,AccountOneFill=1,EvapStations="10006,100",ContentAreaSeepage="0,0,0;0,0,0;1000,46,0;1500,60,0;2222,76,0;2500,96,0;3000,108,0;3500,121,0;4000,133,0;9999999,133,0",IfNotFound=Warn)
# #
# # ROAN CREEK RESERVOIR (CHEVRON)
# SetReservoirStation(ID="7003602",Name="Roan Creek Res",RiverNodeID="ID",OnOff=1,OneFillRule=4,DailyID="5",ContentMin=0,ContentMax=71390,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Active",AccountMax=33773,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10005,100",ContentAreaSeepage="0,0,0;0,0,0;10000,330,0;20000,650,0;40000,970,0;60000,1300,0;80000,1570,0;9999999,1570,0",IfNotFound=Warn)
# #
# # PARACHUTE CREEK RESERVOIR (CHEVRON)
# SetReservoirStation(ID="3903943",Name="Parachute Creek Res",RiverNodeID="ID",OnOff=1,OneFillRule=4,DailyID="5",ContentMin=0,ContentMax=33773,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Chevron",AccountMax=16886.50,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10005,100",ContentAreaSeepage="0,0,0;0,0,0;4738,197,0;16849,409,0;38313,664,0;9999999,664,0",IfNotFound=Warn)
# SetReservoirStation(ID="3903943",AccountID=2,AccountName="Other",AccountMax=16886.50,AccountInitial=0,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# #
# WriteReservoirStationsToStateMod(OutputFile="..\statemod\cm2015B.res")
#
# -----------------------------------------------------------------------------
# HydroBase database is: HydroBase_CO_20150304 on Logan_Laptop
# HydroBase.db_version:  design version: 20141201  last data change: 20150304
# HydroBase table structure for software is at least 2013040420130404
# HydroBase input name is "".
# Stored procedures are being used.
# -----------------------------------------------------------------------------
#
#------------------------------------------------
#>
#> *************************************************************
#>  StateMod Reservoir Station file
#>
#>  Card 1   format:  (a12, a24, a12, i8, f8.0, 1x, a12)
#>
#>  ID       cresid:  Reservoir Id
#>  Name     resnam:  Reservoir name
#>  Riv ID    cgoto:  Node where Reservoir is located
#>  On/Off   iressw:  Switch 0 = off
#>                           1 = on, do not adjust for dead storage
#>                               do not store above rervoir targets
#>                           2 = do not store above rervoir targets
#>                               adjust maximum ownership and initial
#>                               storage of the last account by the
#>                               dead storage volume
#>                           3 = on, do not adjust for dead storage
#>                               do store above rervoir targets
#>                               (Note: in conjunction with an
#>                               operational release for targets this
#>                               results in a 'paper fill' activity.)
#>  Admin #   rdate:  Administration date for 1 fill rule
#>  Daily ID cresdy:  Identifier for daily time series.
#>
#>  Card 2 format:  (24x, 4f8.0, 4i8)
#>
#>  VolMin   volmin:  Min storage (ac-ft)
#>  VolMax   volmax:  Max storage (ac-ft)
#>  FloMax   flomax:  Max discharge (cfs)
#>  DeadSt   deadst:  Dead storage (ac-ft)
#>  NumOwner nowner:  Number of owners
#>  NumEva   nevapo:  Number of evaporation stations
#>  NumPre   nprecp:  Number of precipitation stations
#>  NumTable nrange:  Number of area capacity values
#>
#>  Card 3 format:  (12x, a12, 3f8.0, i8)
#>
#>  OwnName  ownnam:  Owner name
#>  OwnMax   ownmax:  Maximum storage for that owner (ac-ft)
#>  Sto-1    curown:  Initial storage for that owner (ac-ft)
#>  EvapTyp  pcteva:  Evaporation distribution
#>  FillTyp   n2own:  Ownership type 1=First fill; 2=Second fill
#>
#>  Card 4  format:  (24x, a12, f8.0)
#>
#>  Evap ID  cevar:  Evaporation station
#>  EvapWt  weigev:  Evaporation station weight (%%)
#>
#>  Card 5 format:  (24x, a12, f8.0)
#>
#>  Prec ID   cprer:  Precipitation station
#>  PrecWt   weigpr:  Precipitation station weight (%%)
#>
#>  Card 6 format:  (24x, 3f8.0)
#>
#>  Cont     conten:  Content (ac-ft)
#>  Area    surarea:  Area (ac)
#>  Seep    seepage:  Seepage (ac-ft)
#>
#> *************************************************************
#>
#>    ID              Name              Node     On/Off  RDate       DailyID
#>---------eb----------------------eb----------eb------eb------exb----------e
#>                       VolMin  VolMax  FloMax  DeadSt NumOwner NumEva  NumPre NumTable
#>xxxxxxxxxxxxxxxxxxxxxxb------eb------eb------eb------eb------eb------eb------eb------e
#>                         OwnName   OwnMax   Sto-1 EvapTyp FillTyp
#>xxxxxxxxxxxxxxxxxxxxxxb----------eb------eb------eb------eb------e
#>                        Evap Id    EvapWt
#>xxxxxxxxxxxxxxxxxxxxxxb----------eb------e
#>                        Prec Id    PrecWt
#>xxxxxxxxxxxxxxxxxxxxxxb----------eb------e
#>                        Cont    Area    Seep
#>xxxxxxxxxxxxxxxxxxxxxxb------eb------eb------e
#>EndHeader
#>
3603543     GREEN MTN RES           3603543            3      4. 5
                              0. 154645.   4010.      0.       6       1       0      14
            Hist_Users    66000.      0.       0       1
            CBT_Pool      52000.  48095.       0       1
            Contract      20000.  19453.       0       1
            Silt_Proj      5000.   4952.       0       1
            Inactive      11645.  10537.       0       1
            SurplusFish   66000.      0.       0       1
            Evaporation 10008           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     291.   20.00       0
            CAP-AREA  2     938.   47.00       0
            CAP-AREA  3    2316.   95.00       0
            CAP-AREA  4    4912.     170       0
            CAP-AREA  5    9366.     282       0
            CAP-AREA  6   16557.     445       0
            CAP-AREA  7   26999.     596       0
            CAP-AREA  8   40845.     809       0
            CAP-AREA  9   59397.    1060       0
            CAP-AREA 10   83777.    1375       0
            CAP-AREA 11  114862.    1755       0
            CAP-AREA 12  153639.    2124       0
            CAP-AREA 13 9999999.    2124       0
3603570     CONT_HOOSIER_BLUE_RES   3603570            1      4. 5
                              0.   2113. 999999.      0.       3       1       0       3
            Active         2140.      0.       0       1
            CSprings-OOP   2100.   1850.       0       1
            MOA_Rel         250.    250.      -1       1
            Evaporation 10008           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    2140.     214       0
            CAP-AREA  2 9999999.     214       0
3603575     CLINTON GULCH RESERVOIR 3603575            1      4. 5
                              0.   4300. 999999.      0.       9       1       0      14
            Breck-Town      390.      0.       0       1
            Dillon-Town      60.     52.       0       1
            Silverthorne    165.    142.       0       1
            Breck-Ski       455.    392.       0       1
            Copper_Mtn      490.    422.       0       1
            Keystone       1305.   1305.       0       1
            Winter_Park     270.    233.       0       1
            Summit_Co.      465.    401.       0       1
            Dead_Pool       700.    601.       0       1
            Evaporation 10008           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    50.00    3.00       0
            CAP-AREA  2     100.    5.00       0
            CAP-AREA  3     175.    8.00       0
            CAP-AREA  4     210.   14.00       0
            CAP-AREA  5     400.   22.00       0
            CAP-AREA  6     710.   31.00       0
            CAP-AREA  7    1075.   42.00       0
            CAP-AREA  8    1580.   53.00       0
            CAP-AREA  9    2110.   65.00       0
            CAP-AREA 10    2820.   74.00       0
            CAP-AREA 11    3630.   84.00       0
            CAP-AREA 12    4300.   94.00       0
            CAP-AREA 13 9999999.   94.00       0
3604512     DILLON RESERVOIR        3604512            1      4. 5
                              0. 257000.   1940.      0.       5       1       0      15
            Denver/RT    252015.      0.       0       1
            Summit_Co.     1021.    728.       0       1
            Dead_Pool      3269.   2332.       0       1
            1000_acft      1000.    157.       0       1
            Denver-OOP1  154645.   2228.       0       1
            Evaporation 10008           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    3269.     167       0
            CAP-AREA  2    8207.     376       0
            CAP-AREA  3   11964.     472       0
            CAP-AREA  4   20488.     635       0
            CAP-AREA  5   31293.     794       0
            CAP-AREA  6   44471.     958       0
            CAP-AREA  7   60194.    1121       0
            CAP-AREA  8   78357.    1280       0
            CAP-AREA  9   98768.    1442       0
            CAP-AREA 10  122199.    1668       0
            CAP-AREA 11  159555.    2076       0
            CAP-AREA 12  207326.    2658       0
            CAP-AREA 13  257305.    3233       0
            CAP-AREA 14 9999999.    3233       0
36_ARC001   36_ARC001               36_ARC001          1     -1. 5
                              0.   8702. 999999.      0.       1       1       0       3
            36_ARC001      8702.   8702.       0       1
            Evaporation 10008           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    8702.     348       0
            CAP-AREA  2 9999999.     348       0
3703639     WOLCOTT RESERVOIR       3703639            0      4. 5
                              0.  65975. 999999.      0.       1       1       0       3
            Active        65975.      0.       0       1
            Evaporation 10006           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1   65975.    6597       0
            CAP-AREA  2   99999.    6597       0
3703699     EAGLE PARK              3703699            0      4. 5
                              0.   3148. 999999.      0.       4       1       0       3
            Eagle_R_W&S     330.      0.       0       1
            UERRWA          383.      0.       0       1
            Vail_Valley    1100.      0.       0       1
            River_Dist      200.      0.       0       1
            Evaporation 10008           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    3148.     315       0
            CAP-AREA  2    9999.     315       0
3704516     HOMESTAKE PROJ RESERVOIR3704516            1      4. 5
                              0.  43600. 999999.      0.       3       1       0      14
            CS_&_Aurora   42881.      0.       0       1
            Dead_Pool       211.    205.       0       1
            HR_GMR        21440.      0.       0       1
            Evaporation 10006           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     838.   69.00       0
            CAP-AREA  2    2609.     107       0
            CAP-AREA  3    5035.     134       0
            CAP-AREA  4    7973.     160       0
            CAP-AREA  5   11343.     179       0
            CAP-AREA  6   15136.     200       0
            CAP-AREA  7   19365.     222       0
            CAP-AREA  8   24122.     251       0
            CAP-AREA  9   29419.     277       0
            CAP-AREA 10   35246.     304       0
            CAP-AREA 11   41597.     329       0
            CAP-AREA 12   43092.     334       0
            CAP-AREA 13 9999999.     334       0
37_ARC002   37_ARC002               37_ARC002          1     -1. 5
                              0.   6671. 999999.      0.       1       1       0       3
            37_ARC002      6671.   6671.       0       1
            Evaporation 10006           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    6671.     267       0
            CAP-AREA  2 9999999.     267       0
3803713     RUEDI_RESERVOIR         3803713            1      4. 5
                              0. 102373.   1390.      0.       6       1       0      15
            Rnd_1&2_Cont  30263.      0.       0       1
            Replacement   28000.  26575.       0       1
            Unalloc/Dead  28698.  21713.       0       1
            CWCB_Fish      5413.   5142.       0       1
            Unalloc/5k     5000.      0.       0       1
            USFWS_5k_4/5   5000.      0.       0       1
            Evaporation 10006           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    63.00    7.00       0
            CAP-AREA  2     516.   84.00       0
            CAP-AREA  3    2966.     162       0
            CAP-AREA  4    6988.     241       0
            CAP-AREA  5   12458.     303       0
            CAP-AREA  6   19211.     376       0
            CAP-AREA  7   27563.     459       0
            CAP-AREA  8   37538.     541       0
            CAP-AREA  9   49233.     631       0
            CAP-AREA 10   62851.     728       0
            CAP-AREA 11   78513.     841       0
            CAP-AREA 12   96500.     959       0
            CAP-AREA 13  102373.     998       0
            CAP-AREA 14 9999999.     998       0
38_ARC003   38_ARC003               38_ARC003          1     -1. 5
                              0.  13074. 999999.      0.       1       1       0       3
            38_ARC003     13074.  13074.       0       1
            Evaporation 10006           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1   13074.     523       0
            CAP-AREA  2 9999999.     523       0
3903505     GRASS VALLEY RESERVOIR  3903505            1     11. 5
                              0.   5920. 999999.      0.       1       1       0       8
            Farmers        5920.   2233.       0       1
            Evaporation 10005           100.
            CAP-AREA  0     0.00   33.00       0
            CAP-AREA  1     363.   65.00       0
            CAP-AREA  2    1155.   94.00       0
            CAP-AREA  3    2244.     124       0
            CAP-AREA  4    3644.     156       0
            CAP-AREA  5    5416.     199       0
            CAP-AREA  6    5920.     208       0
            CAP-AREA  7 9999999.     208       0
3903508     RIFLE GAP RESERVOIR     3903508            1     11. 5
                              0.  13602. 999999.      0.       2       1       0      12
            Silt_Pool     12168.      0.       0       1
            Dead_Pool      1434.   1382.       0       1
            Evaporation 10005           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     3.00    1.00       0
            CAP-AREA  2    37.00    6.00       0
            CAP-AREA  3     188.   27.00       0
            CAP-AREA  4     651.   70.00       0
            CAP-AREA  5    1692.     134       0
            CAP-AREA  6    3268.     179       0
            CAP-AREA  7    5211.     211       0
            CAP-AREA  8    7522.     253       0
            CAP-AREA  9   10297.     303       0
            CAP-AREA 10   13602.     359       0
            CAP-AREA 11 9999999.     359       0
3903508_Ex                          3903508_Ex         1     11. 5
                              0. 999999. 999999.      0.       1       0       0       2
            Exchange     999999.      0.      -1       1
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1  999999.   99999       0
3903943     Parachute Creek Res     3903943            1      4. 5
                              0.  33773. 999999.      0.       2       1       0       6
            Chevron       16887.      0.       0       1
            Other         16887.      0.       0       1
            Evaporation 10005           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     0.00    0.00       0
            CAP-AREA  2    4738.     197       0
            CAP-AREA  3   16849.     409       0
            CAP-AREA  4   38313.     664       0
            CAP-AREA  5 9999999.     664       0
39_ARC004   39_ARC004               39_ARC004          1     -1. 5
                              0.   2236. 999999.      0.       1       1       0       3
            39_ARC004      2236.   2236.       0       1
            Evaporation 10005           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    2236.   89.40       0
            CAP-AREA  2 9999999.   89.40       0
45_ARC005   45_ARC005               45_ARC005          1     -1. 5
                              0.   2054. 999999.      0.       1       1       0       3
            45_ARC005      2054.   2054.       0       1
            Evaporation 10005           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    2054.   82.20       0
            CAP-AREA  2 9999999.   82.20       0
5003668     WOLFORD_MOUNTAIN_RES    5003668            1      4. 5
                              0.  65985.    992.      0.       9       1       0      11
            West_Slope    39796.      0.       0       1
            Denver        25610.  25035.       0       1
            Fish_Account   3000.   2670.       0       1
            Fish_Account   3000.   2670.       0       1
            Denver_R1      5000.      0.       0       1
            Denver_R2     20610.      0.       0       1
            C.Springs      1750.    875.       0       1
            C.Springs_B     250.      0.       0       1
            C.Springs_R    1750.      0.       0       1
            Evaporation 10008           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1   23206.     753       0
            CAP-AREA  2   27112.     810       0
            CAP-AREA  3   31307.     869       0
            CAP-AREA  4   35910.     973       0
            CAP-AREA  5   41051.    1084       0
            CAP-AREA  6   46761.    1201       0
            CAP-AREA  7   52069.    1323       0
            CAP-AREA  8   59993.    1447       0
            CAP-AREA  9   65985.    1550       0
            CAP-AREA 10 9999999.    1550       0
50_ARC006   50_ARC006               50_ARC006          1     -1. 5
                              0.  11481. 999999.      0.       1       1       0       3
            50_ARC006     11481.  11481.       0       1
            Evaporation 10008           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1   11481.     459       0
            CAP-AREA  2 9999999.     459       0
5103686     MEADOW CREEK RESERVOIR  5103686            1      4. 5
                              0.   5930. 999999.      0.       3       1       0      14
            Denver/Engl    4780.      0.       0       1
            VailDitch       850.    819.       0       1
            Dead_Pool       300.    292.       0       1
            Evaporation 10009           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     500.   54.00       0
            CAP-AREA  2    1000.   72.00       0
            CAP-AREA  3    1500.   85.00       0
            CAP-AREA  4    2000.   95.00       0
            CAP-AREA  5    2500.     106       0
            CAP-AREA  6    3000.     115       0
            CAP-AREA  7    3500.     128       0
            CAP-AREA  8    4000.     141       0
            CAP-AREA  9    4500.     155       0
            CAP-AREA 10    5000.     166       0
            CAP-AREA 11    5500.     179       0
            CAP-AREA 12    5700.     186       0
            CAP-AREA 13 9999999.     186       0
5103695     CBT SHADOW MOUNTAIN LAKE5103695            1      4. 5
                              0.  18369. 999999.      0.       2       1       0      13
            Account        1839.      0.       0       1
            Dead_Pool     16530.  16397.       0       1
            Evaporation 10009           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     4.00    2.00       0
            CAP-AREA  2    76.00   27.00       0
            CAP-AREA  3     506.     145       0
            CAP-AREA  4     750.     190       0
            CAP-AREA  5    2069.     480       0
            CAP-AREA  6    5591.     929       0
            CAP-AREA  7    8628.    1096       0
            CAP-AREA  8   10932.    1208       0
            CAP-AREA  9   14708.    1808       0
            CAP-AREA 10   16530.    1830       0
            CAP-AREA 11   18369.    1852       0
            CAP-AREA 12 9999999.    1852       0
5103709     WILLIAMS FORK RESERVOIR 5103709            1      4. 5
                              0.  96822.   1860.      0.       5       1       0      16
            Denver        99765.      0.       0       1
            Henderson      2200.   1723.       0       1
            WF_Fish_Temp      0.      0.       0       1
            WF_GMR1       10000.      0.       0       1
            WF_GMR2       25000.      0.       0       1
            Evaporation 10008           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    11.00    3.00       0
            CAP-AREA  2    95.00   15.00       0
            CAP-AREA  3    1070.   86.00       0
            CAP-AREA  4    2102.     123       0
            CAP-AREA  5    3578.     174       0
            CAP-AREA  6    5707.     257       0
            CAP-AREA  7    8659.     331       0
            CAP-AREA  8   12395.     417       0
            CAP-AREA  9   16992.     504       0
            CAP-AREA 10   29182.     715       0
            CAP-AREA 11   45725.     943       0
            CAP-AREA 12   80315.    1388       0
            CAP-AREA 13   84565.    1446       0
            CAP-AREA 14   96822.    1628       0
            CAP-AREA 15 9999999.    1628       0
5103710     CBT WILLOW CREEK RESERVO5103710            1     -1. 5
                              0.  10553. 999999.      0.       2       1       0      12
            CBT_Pool       3329.      0.       0       1
            Dead_Pool      7224.   6123.       0       1
            Evaporation 10009           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    12.00    3.00       0
            CAP-AREA  2     117.   21.00       0
            CAP-AREA  3     495.   58.00       0
            CAP-AREA  4    1290.   96.00       0
            CAP-AREA  5    2345.     114       0
            CAP-AREA  6    3577.     133       0
            CAP-AREA  7    5035.     158       0
            CAP-AREA  8    6813.     199       0
            CAP-AREA  9    7891.     232       0
            CAP-AREA 10   10553.     303       0
            CAP-AREA 11 9999999.     303       0
5104055     CBT GRANBY RESERVOIR    5104055            1     -1. 5
                              0. 539758.   2460.      0.       3       1       0      14
            CBT_Pool     465568.      0.       0       1
            Dead_Pool     74190.  72670.       0       1
            Fish_Account   5413.      0.       0       1
            Evaporation 10009           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     109.   22.00       0
            CAP-AREA  2    1406.     115       0
            CAP-AREA  3    5175.     259       0
            CAP-AREA  4   11792.     403       0
            CAP-AREA  5   23661.     869       0
            CAP-AREA  6   53574.    2061       0
            CAP-AREA  7  105132.    3117       0
            CAP-AREA  8  178168.    4165       0
            CAP-AREA  9  271459.    5182       0
            CAP-AREA 10  385040.    6155       0
            CAP-AREA 11  483058.    6943       0
            CAP-AREA 12  539758.    7256       0
            CAP-AREA 13 9999999.    7256       0
51_ARC007   51_ARC007               51_ARC007          1     -1. 5
                              0.   8480. 999999.      0.       1       1       0       3
            51_ARC007      8480.   8480.       0       1
            Evaporation 10009           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    8480.     339       0
            CAP-AREA  2 9999999.     339       0
52_ARC008   52_ARC008               52_ARC008          1     -1. 5
                              0.    821. 999999.      0.       1       1       0       3
            52_ARC008       821.    821.       0       1
            Evaporation 10006           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     821.   32.80       0
            CAP-AREA  2 9999999.   32.80       0
53_ARC009   53_ARC009               53_ARC009          1     -1. 5
                              0.   8389. 999999.      0.       1       1       0       3
            53_ARC009      8389.   8389.       0       1
            Evaporation 10006           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    8389.     336       0
            CAP-AREA  2 9999999.     336       0
7003602     Roan Creek Res          7003602            1      4. 5
                              0.  71390. 999999.      0.       1       1       0       8
            Active        33773.      0.       0       1
            Evaporation 10005           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     0.00    0.00       0
            CAP-AREA  2   10000.     330       0
            CAP-AREA  3   20000.     650       0
            CAP-AREA  4   40000.     970       0
            CAP-AREA  5   60000.    1300       0
            CAP-AREA  6   80000.    1570       0
            CAP-AREA  7 9999999.    1570       0
7203839     LEON_LAKEAGG_RES        7203839            1      4. 5
                              0.   2904. 999999.      0.       1       1       0       3
            Active         2904.   1500.       0       1
            Evaporation 10006           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    2904.     200       0
            CAP-AREA  2 9999999.     200       0
7203842     MONUMENTAGG_RES         7203842            1      4. 5
                              0.    987. 999999.      0.       1       1       0       3
            Active          987.    500.       0       1
            Evaporation 10006           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     987.   90.00       0
            CAP-AREA  2 9999999.   90.00       0
7203844     VEGA RESERVOIR          7203844            1     11. 5
                              0.  34131. 999999.      0.       2       1       0      15
            Project_Irr   33311.      0.       0       1
            Dead_Pool       820.    672.       0       1
            Evaporation 10006           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     7.00    2.00       0
            CAP-AREA  2    46.00    7.00       0
            CAP-AREA  3     173.   20.00       0
            CAP-AREA  4     485.   43.00       0
            CAP-AREA  5    1163.   95.00       0
            CAP-AREA  6    2490.     169       0
            CAP-AREA  7    4574.     253       0
            CAP-AREA  8    7514.     336       0
            CAP-AREA  9   11345.     433       0
            CAP-AREA 10   16320.     567       0
            CAP-AREA 11   22621.     698       0
            CAP-AREA 12   30326.     844       0
            CAP-AREA 13   34716.     912       0
            CAP-AREA 14 9999999.     912       0
7203904AG   BONHAMAGGREGATED_RES    7203904AG          1      4. 5
                              0.   6778. 999999.      0.       1       1       0      16
            Active         6778.   6778.       0       1
            Evaporation 10006           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     0.00    0.00       0
            CAP-AREA  2    1000.   46.00       0
            CAP-AREA  3    1500.   60.00       0
            CAP-AREA  4    2222.   76.00       0
            CAP-AREA  5    2500.   96.00       0
            CAP-AREA  6    3000.     108       0
            CAP-AREA  7    3500.     121       0
            CAP-AREA  8    4000.     133       0
            CAP-AREA  9    4500.     143       0
            CAP-AREA 10    5000.     151       0
            CAP-AREA 11    5500.     161       0
            CAP-AREA 12    6000.     169       0
            CAP-AREA 13    6500.     177       0
            CAP-AREA 14    7000.     178       0
            CAP-AREA 15 9999999.     178       0
7203961     JERRY_CREEK_RES         7203961            1      4. 5
                              0.   8623. 999999.    163.       1       1       0       6
            Active         8460.      0.       0       1
            Evaporation 10006           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    1000.   46.00       0
            CAP-AREA  2    3000.     108       0
            CAP-AREA  3    4000.     133       0
            CAP-AREA  4    5000.     151       0
            CAP-AREA  5    8500.     180       0
7204033AG   COTTONWOODAGGREG_RES    7204033AG          1      4. 5
                              0.   3812. 999999.      0.       1       1       0      10
            Active         3812.   3812.       0       1
            Evaporation 10006           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     0.00    0.00       0
            CAP-AREA  2    1000.   46.00       0
            CAP-AREA  3    1500.   60.00       0
            CAP-AREA  4    2222.   76.00       0
            CAP-AREA  5    2500.   96.00       0
            CAP-AREA  6    3000.     108       0
            CAP-AREA  7    3500.     121       0
            CAP-AREA  8    4000.     133       0
            CAP-AREA  9 9999999.     133       0
72_ARC010   72_ARC010               72_ARC010          1     -1. 5
                              0.  25664. 999999.      0.       1       1       0       3
            72_ARC010     25664.  25664.       0       1
            Evaporation 10006           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1   25664.    1027       0
            CAP-AREA  2 9999999.    1027       0
72_ASC001   72_ASC001               72_ASC001          1     -1. 5
                              0.   2261. 999999.      0.       1       1       0       3
            72_ASC001      2261.   2261.       0       1
            Evaporation 10006           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    2261.     226       0
            CAP-AREA  2 9999999.     226       0
