#HeaderRevision 0
#
# File generated by...
# program:      StateDMI 3.12.02 (2013-04-17)
# user:         CTS
# date:         Tue Jun 07 08:33:08 MDT 2016
# host:         Katie
# directory:    C:\Google Drive\CDSS\gm2015\Reservoirs
# command line: StateDMI
# 
#----
# -----------------------------------------------------------------------
# Command file name: "C:\Google Drive\CDSS\gm2015\Reservoirs\Bres.commands.StateDMI"
# Commands: 
# # Bres.commands.StateDMI
# #
# # Creates the reservoir station file for the Gunnison River monthly models
# # Initial reservoir contents are set to average September EOM contents
# #
# #  Step 1 - read reservoirs from network file and sort alphabetically
# #
# ReadReservoirStationsFromNetwork(InputFile="..\network\gm2015.net")
# SortReservoirStations(Order=Ascending)
# #
# #  Step 2 - read reservoir information from HydroBase
# #
# FillReservoirStationsFromHydroBase(ID="*")
# #
# #  Step 3 - set reservoir information not available in HydroBase including min/max
# #           content, starting content, and account information
# #
# #RESERVOIR INFORMATION
# #AREA/CAP FOR MORROW & CRYSTAL TAKEN FROM HYDROSPHERE REPORT
# #AREA/CAP FOR RIDGWAY BASED ON WWWHEELER MEMO 1.15-20
# #AREA/CAP FOR SILVERJACK BASED ON WWWHEELER MEMO 1.15-19
# #
# #FRUIT GROWERS RES.
# #  CRWAS Model Revision
# #            create accounts for acreage-based allotment ditch services
# SetReservoirStation(ID="4003365",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=4540,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Irrigation",AccountMax=4460,AccountInitial=4460,AccountEvap=0,AccountOneFill=1,EvapStations="10009,100",ContentAreaSeepage="0,0,0;4792,476,0;9999999,476,0",IfNotFound=Warn)
# SetReservoirStation(ID="4003365",AccountID=2,AccountName="Dead_Pool",AccountMax=80,AccountInitial=80,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# #
# #FRUITLAND RES.(aka Gould)
# SetReservoirStation(ID="4003395",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=8100,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Irrigation",AccountMax=8100,AccountInitial=8100,AccountEvap=0,AccountOneFill=1,EvapStations="10009,100",ContentAreaSeepage="0,0,0;9900,200,0;9999999,200,0",IfNotFound=Warn)
# #
# #MORROW POINT
# #  CRWAS Model Revision
# #            create accounts for acreage-based allotment ditch services
# SetReservoirStation(ID="6203545",OnOff=1,OneFillRule=11,DailyID="5",ContentMin=0,ContentMax=118764,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Acc1",AccountMax=42120,AccountInitial=42120,AccountEvap=0,AccountOneFill=1,EvapStations="10011,100",ContentAreaSeepage="0.00,0.00,0;5000.,111,0;10000.,186,0;15000.,222,0;20000.,264,0;25000.,313,0;30000.,352,0;40000.,411,0;50000.,471,0;60000.,531,0;70000.,583,0;90000.,679,0;100000.,727,0;110000.,781,0;118764.,838,0;9999999.,838,0",IfNotFound=Warn)
# SetReservoirStation(ID="6203545",AccountID=2,AccountName="Dead_Pool",AccountMax=76644,AccountInitial=76644,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# #
# #CRYSTAL RES.
# #  CRWAS Model Revision
# #            create accounts for acreage-based allotment ditch services
# SetReservoirStation(ID="6203578",OnOff=1,OneFillRule=11,DailyID="5",ContentMin=0,ContentMax=25236,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Acc1",AccountMax=25236,AccountInitial=25236,AccountEvap=0,AccountOneFill=1,EvapStations="10011,100",ContentAreaSeepage="0.00,0.00,0;2000.,151,0;4000.,172,0;6000.,191,0;8000.,210,0;10000.,229,0;12000.,250,0;14000.,267,0;16000.,287,0;18000.,304,0;20000.,322,0;22000.,336,0;24000.,350,0;25236.,350,0;9999999.,350,0",IfNotFound=Warn)
# #
# #SILVERJACK RES.
# SetReservoirStation(ID="6203548",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=13520,ReleaseMax=280,DeadStorage=0,AccountID=1,AccountName="Irrigation",AccountMax=12837,AccountInitial=12837,AccountEvap=0,AccountOneFill=1,EvapStations="10012,100",ContentAreaSeepage="0.00,0.00,0;1200.,62.00,0;1930.,83.00,0;2870.,107,0;4070.,133,0;5560.,164,0;7350.,195,0;9470.,229,0;11950.,268,0;13900.,293,0;9999999.,293,0",IfNotFound=Warn)
# SetReservoirStation(ID="6203548",AccountID=2,AccountName="Dead_Pool",AccountMax=683,AccountInitial=683,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# #
# #RIDGWAY RES.
# SetReservoirStation(ID="6803675",Name="Ridgway",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=84467,ReleaseMax=500,DeadStorage=0,AccountID=1,AccountName="Project7",AccountMax=28100,AccountInitial=28100,AccountEvap=0,AccountOneFill=1,EvapStations="10012,100",ContentAreaSeepage="0.00,0.00,0;1430.,85.00,0;4150.,203,0;9657.,345,0;17637.,457,0;27841.,572,0;40315.,684,0;55382.,815,0;73146.,971,0;84467.,1063,0;85897.,1063,0;9999999.,1063,0",IfNotFound=Warn)
# SetReservoirStation(ID="6803675",AccountID=2,AccountName="UVWUA",AccountMax=11200,AccountInitial=11200,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="6803675",AccountID=3,AccountName="Recreation",AccountMax=19200,AccountInitial=19200,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="6803675",AccountID=4,AccountName="Dead_Pool",AccountMax=25067,AccountInitial=25067,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="6803675",AccountID=5,AccountName="Unallocated",AccountMax=900,AccountInitial=900,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="6803675",AccountID=6,AccountName="Exchange",AccountMax=28100,AccountInitial=0,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# #
# #CRAWFORD RES.
# SetReservoirStation(ID="4003553",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=14395,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Irrigation",AccountMax=10350,AccountInitial=10350,AccountEvap=0,AccountOneFill=1,EvapStations="10009,100",ContentAreaSeepage="0.00,0.00,0;116.,13.00,0;602.,41.00,0;1126.,65.00,0;1924.,98.00,0;3087.,135,0;4714.,193,0;6926.,251,0;9745.,313,0;14633.,406,0;9999999.,406,0",IfNotFound=Warn)
# SetReservoirStation(ID="4003553",AccountID=2,AccountName="Recreation",AccountMax=4045,AccountInitial=4045,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# #
# #PAONIA RES.
# SetReservoirStation(ID="4003416",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=18700,ReleaseMax=1130,DeadStorage=0,AccountID=1,AccountName="Fire_Mtn",AccountMax=12650,AccountInitial=12650,AccountEvap=0,AccountOneFill=1,EvapStations="10011,100",ContentAreaSeepage="0.00,0.00,0;184.,23.00,0;843.,44.00,0;2071.,89.00,0;4877.,177,0;6896.,227,0;9319.,258,0;12053.,289,0;15052.,311,0;20950.,333,0;9999999.,333,0",IfNotFound=Warn)
# SetReservoirStation(ID="4003416",AccountID=2,AccountName="Ragged_Mtn",AccountMax=2000,AccountInitial=2000,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="4003416",AccountID=3,AccountName="Endangered_F",AccountMax=1500,AccountInitial=1500,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="4003416",AccountID=4,AccountName="Dead_Pool",AccountMax=2550,AccountInitial=2550,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# #
# #TAYLOR PARK RES.
# # Changed account distribution from all 3 accounts to just account 1(USA) and deadpool, based on BuRec comments 3/3/99 ra
# SetReservoirStation(ID="5903666",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=108490,ReleaseMax=1500,DeadStorage=0,AccountID=1,AccountName="UVWUA",AccountMax=106200,AccountInitial=106200,AccountEvap=0,AccountOneFill=1,EvapStations="10010,100",ContentAreaSeepage="0.00,0.00,0;20000.,639,0;30000.,846,0;40000.,1061,0;50000.,1274,0;60000.,1451,0;70000.,1603,0;80000.,1742,0;90000.,1870,0;108490.,2060,0;9999999.,2060,0",IfNotFound=Warn)
# SetReservoirStation(ID="5903666",AccountID=2,AccountName="Dead_Pool",AccountMax=2290,AccountInitial=2290,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="5903666",AccountID=3,AccountName="UGRWCD",AccountMax=106200,AccountInitial=0,AccountEvap=0,AccountOneFill=2,IfNotFound=Warn)
# #
# #BLUE MESA RES.
# # Changed account distribution from all 3 accounts to just accounts 1(USA) and 2 (Dead), based on BuRec comments 3/3/99 ra
# SetReservoirStation(ID="6203532",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=940800,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="USA",AccountMax=748530,AccountInitial=748530,AccountEvap=0,AccountOneFill=1,EvapStations="10011,100",IfNotFound=Warn)
# SetReservoirStation(ID="6203532",AccountID=2,AccountName="Dead_Pool",AccountMax=192270,AccountInitial=192270,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# SetReservoirStation(ID="6203532",AccountID=3,AccountName="UVWUA",AccountMax=106200,AccountInitial=0,AccountEvap=0,AccountOneFill=2,IfNotFound=Warn)
# #
# #OVERLAND RES.
# # ew 07/2009 increased reservoir max to 6200 per WC as part of CRWAS
# #
# SetReservoirStation(ID="4003399",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=6200,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Irrigation",AccountMax=6148,AccountInitial=6148,AccountEvap=0,AccountOneFill=1,EvapStations="10010,100",IfNotFound=Warn)
# SetReservoirStation(ID="4003399",AccountID=2,AccountName="Dead_Pool",AccountMax=52,AccountInitial=52,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# #
# #CERRO RES.
# #Surface area and capacity taken from Div 4 dam safety records
# SetReservoirStation(ID="41_Cerro",Name="Cerro",RiverNodeID="41_Cerro",OnOff=1,OneFillRule=11,DailyID="5",ContentMin=0,ContentMax=650,ReleaseMax=2,DeadStorage=0,AccountID=1,AccountName="Project7",AccountMax=650,AccountInitial=650,AccountEvap=0,AccountOneFill=1,EvapStations="10012,100",ContentAreaSeepage="0.00,0.00,0;650.,28.00,0;9999999.,28.00,0",IfNotFound=Warn)
# #
# #FAIRVIEW RES.
# #Surface area and capacity taken from Div 4 dam safety records
# SetReservoirStation(ID="41_Fairvw",Name="Fairview",RiverNodeID="41_Fairvw",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=350,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Project7",AccountMax=350,AccountInitial=350,AccountEvap=0,AccountOneFill=1,EvapStations="10012,100",ContentAreaSeepage="0.00,0.00,0;350.,36.00,0;999999.,36.00,0",IfNotFound=Warn)
# #
# #
# ## Tomichi Creek reservoirs added to model
# # Assumed depth of 25ft according to Div4 Dam Safety Records
# #
# #Needle Creek Reservoir
# SetReservoirStation(ID="2803593",OnOff=1,OneFillRule=11,DailyID="5",ContentMin=0,ContentMax=1298,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Acc1",AccountMax=1298,AccountInitial=1298,AccountEvap=0,AccountOneFill=1,EvapStations="10010,100",ContentAreaSeepage="0,0,0;1298,52,0;9999999,52,0",IfNotFound=Warn)
# #
# #Vouga Reservoir (Razor Creek)
# SetReservoirStation(ID="2803595",OnOff=1,OneFillRule=11,DailyID="5",ContentMin=0,ContentMax=1450,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Acc1",AccountMax=1450,AccountInitial=1450,AccountEvap=0,AccountOneFill=1,EvapStations="10010,100",ContentAreaSeepage="0,0,0;1450,58,0;9999999,58,0",IfNotFound=Warn)
# #
# #Hot Springs Reservoir
# SetReservoirStation(ID="2803590",OnOff=1,OneFillRule=11,DailyID="5",ContentMin=0,ContentMax=1029,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Acc1",AccountMax=1029,AccountInitial=1029,AccountEvap=0,AccountOneFill=1,EvapStations="10010,100",ContentAreaSeepage="0,0,0;1029,41,0;9999999,41,0",IfNotFound=Warn)
# #
# #McDonough Reservoir
# SetReservoirStation(ID="2803591",OnOff=1,OneFillRule=11,DailyID="5",ContentMin=0,ContentMax=1808,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Acc1",AccountMax=1808,AccountInitial=1808,AccountEvap=0,AccountOneFill=1,EvapStations="10010,100",ContentAreaSeepage="0,0,0;1808,72,0;9999999,72,0",IfNotFound=Warn)
# SetReservoirStation(ID="2803592",OnOff=1,OneFillRule=11,DailyID="5",ContentMin=0,ContentMax=1774,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Acc1",AccountMax=1774,AccountInitial=1774,AccountEvap=0,AccountOneFill=1,EvapStations="10010,100",ContentAreaSeepage="0,0,0;1774,71,0;9999999,71,0",IfNotFound=Warn)
# #
# #Upper Dome Reservoir
# SetReservoirStation(ID="2803594",OnOff=1,OneFillRule=11,DailyID="5",ContentMin=0,ContentMax=880,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Acc1",AccountMax=880,AccountInitial=808,AccountEvap=0,AccountOneFill=1,EvapStations="10010,100",ContentAreaSeepage="0,0,0;880,35,0;9999999,35,0",IfNotFound=Warn)
# #
# #Boulder Lake
# SetReservoirStation(ID="2803652",OnOff=1,OneFillRule=11,DailyID="5",ContentMin=0,ContentMax=104,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Acc1",AccountMax=104,AccountInitial=104,AccountEvap=0,AccountOneFill=1,EvapStations="10010,100",ContentAreaSeepage="0,0,0;104,4,0;9999999,4,0",IfNotFound=Warn)
# #
# #Peterson Reservoir
# SetReservoirStation(ID="2803674",OnOff=1,OneFillRule=11,DailyID="5",ContentMin=0,ContentMax=190,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Acc1",AccountMax=190,AccountInitial=190,AccountEvap=0,AccountOneFill=1,EvapStations="10010,100",ContentAreaSeepage="0,0,0;190,8,0;9999999,8,0",IfNotFound=Warn)
# #
# #Lower Dome Reservoir
# SetReservoirStation(ID="2803617",OnOff=1,OneFillRule=11,DailyID="5",ContentMin=0,ContentMax=60,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Acc1",AccountMax=59.5,AccountInitial=59.5,AccountEvap=0,AccountOneFill=1,EvapStations="10010,100",ContentAreaSeepage="0,0,0;60,2,0;9999999,2,0",IfNotFound=Warn)
# #
# #
# #Aggregate reservoirs
# #Depth is an average(25 ft) for reservoirs in Div 4 dam safety records
# #
# # District 28 Aggregated Reservoirs
# SetReservoirStation(ID="28_ARG001",Name="AGG_RES_Tomichi",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=156,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="AGG_RES_Tomichi",AccountMax=156,AccountInitial=156,AccountEvap=0,AccountOneFill=1,EvapStations="10010,100",ContentAreaSeepage="0.00,0.00,0;156.,6,0;9999999.,6,0",IfNotFound=Warn)
# #
# # District 62 Aggregated Reservoirs
# SetReservoirStation(ID="62_ARG001",Name="AGG_RES_Lake",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=6475,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="AGG_RES_Lake",AccountMax=6475,AccountInitial=6475,AccountEvap=0,AccountOneFill=1,EvapStations="10011,100",ContentAreaSeepage="0.00,0.00,0;6475.,259,0;9999999.,259,0",IfNotFound=Warn)
# #
# SetReservoirStation(ID="62_ARG002",Name="AGG_RES_Main",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=6475,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="AGG_RES_Main",AccountMax=6475,AccountInitial=6475,AccountEvap=0,AccountOneFill=1,EvapStations="10011,100",ContentAreaSeepage="0.00,0.00,0;6475.,259,0;9999999.,259,0",IfNotFound=Warn)
# #
# # District 40 Aggregated Reservoirs
# SetReservoirStation(ID="40_ARG001",Name="AGG_RES_Surface",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=23268,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="AGG_RES_Surface",AccountMax=23268,AccountInitial=23268,AccountEvap=0,AccountOneFill=1,EvapStations="10009,100",ContentAreaSeepage="0.00,0.00,0;23268.,931,0;9999999.,931,0",IfNotFound=Warn)
# #
# SetReservoirStation(ID="40_ARG002",Name="AGG_RES_Ngunn",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=23268,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="AGG_RES_Ngunn",AccountMax=23268,AccountInitial=23268,AccountEvap=0,AccountOneFill=1,EvapStations="10009,100",ContentAreaSeepage="0.00,0.00,0;23268.,931,0;9999999.,931,0",IfNotFound=Warn)
# #
# # District 68 Aggregated Reservoirs
# SetReservoirStation(ID="68_ARG001",Name="AGG_RES_UpperUncomp",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=8359,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="AGG_RES_UpperUncomp",AccountMax=8359,AccountInitial=8359,AccountEvap=0,AccountOneFill=1,EvapStations="10012,100",ContentAreaSeepage="0.00,0.00,0;8359.,334,0;9999999.,334,0",IfNotFound=Warn)
# #
# # District 41 Aggregated Reservoirs
# SetReservoirStation(ID="41_ARG001",Name="AGG_RES_Uncomp",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=3226,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="AGG_RES_Uncomp",AccountMax=3226,AccountInitial=3226,AccountEvap=0,AccountOneFill=1,EvapStations="10012,100",ContentAreaSeepage="0.00,0.00,0;3226.,129,0;9999999.,129,0",IfNotFound=Warn)
# #
# # District 42 Aggregated Reservoirs
# SetReservoirStation(ID="42_ARG001",Name="AGG_RES_Kannah",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=17876,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="AGG_RES_Kannah",AccountMax=17876,AccountInitial=17876,AccountEvap=0,AccountOneFill=1,EvapStations="10012,100",ContentAreaSeepage="0.00,0.00,0;17876.,715,0;9999999.,715,0",IfNotFound=Warn)
# #
# # District 59 Aggregated Reservoirs
# SetReservoirStation(ID="59_ARG001",Name="AGG_RES_East",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=9826,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="AGG_RES_East",AccountMax=9826,AccountInitial=9826,AccountEvap=0,AccountOneFill=1,EvapStations="10006,100",ContentAreaSeepage="0.00,0.00,0;9826.,393,0;9999999.,393,0",IfNotFound=Warn)
# #
# #
# #Aggregated stock ponds, average depth of 10 ft.
# #
# # District 62 Aggregated Stock Ponds
# SetReservoirStation(ID="62_ASG001",Name="AGG_STOCK_Main",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=1727,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="AGG_STOCK_Main",AccountMax=1727,AccountInitial=1727,AccountEvap=0,AccountOneFill=1,EvapStations="10012,100",ContentAreaSeepage="0.00,0.00,0;1727.,173,0;9999999.,173,0",IfNotFound=Warn)
# #
# # District 40 Aggregated Stock Ponds
# SetReservoirStation(ID="40_ASG001",Name="AGG_STOCK_Surface",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=1727,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="AGG_STOCK_Surface",AccountMax=1727,AccountInitial=1727,AccountEvap=0,AccountOneFill=1,EvapStations="10012,100",ContentAreaSeepage="0.00,0.00,0;1727.,173,0;9999999.,173,0",IfNotFound=Warn)
# #
# # District 68 Aggregated Stock Ponds
# SetReservoirStation(ID="68_ASG001",Name="AGG_STOCK_UpperUncomp",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=1727,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="AGG_STOCK_UpperUncomp",AccountMax=1727,AccountInitial=1727,AccountEvap=0,AccountOneFill=1,EvapStations="10012,100",ContentAreaSeepage="0.00,0.00,0;1727.,173,0;9999999.,173,0",IfNotFound=Warn)
# #
# # District 41 Aggregated Stock Ponds
# SetReservoirStation(ID="41_ASG001",Name="AGG_STOCK_Uncomp",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=1727,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="AGG_STOCK_Uncomp",AccountMax=1727,AccountInitial=1727,AccountEvap=0,AccountOneFill=1,EvapStations="10012,100",ContentAreaSeepage="0.00,0.00,0;1727.,173,0;9999999.,173,0",IfNotFound=Warn)
# #
# # District 42 Aggregated Stock Ponds
# SetReservoirStation(ID="42_ASG001",Name="AGG_STOCK_Kannah",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=1727,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="AGG_STOCK_Kannah",AccountMax=1727,AccountInitial=1727,AccountEvap=0,AccountOneFill=1,EvapStations="10012,100",ContentAreaSeepage="0.00,0.00,0;1727.,173,0;9999999.,173,0",IfNotFound=Warn)
# #
# #
# #  Reservoirs added for GBIP
# #
# #  West Fork Currant Creek (Gorsuch Reservoir)
# SetReservoirStation(ID="4003527",Name="Gorsuch Reservoir",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=25000,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Irrigation",AccountMax=24000,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10009,100",ContentAreaSeepage="0.00,0.00,0;25000,2500,0;9999999,2500,0",IfNotFound=Warn)
# SetReservoirStation(ID="4003527",AccountID=2,AccountName="Inactive",AccountMax=1000,AccountInitial=0,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# #  Cunningham Gulch Reservoir
# SetReservoirStation(ID="5903660",Name="Cunningham Gulch",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=85,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Irrigation",AccountMax=85,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10006,100",ContentAreaSeepage="0.00,0.00,0;85,50,0;9999999,50,0",IfNotFound=Warn)
# #  Meridian Lake
# SetReservoirStation(ID="5903663",Name="Meridian Lake",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=1380,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Irrigation",AccountMax=1100,AccountInitial=1100,AccountEvap=0,AccountOneFill=1,EvapStations="10006,100",ContentAreaSeepage="0.00,0.00,0;1380,50,0;9999999,50,0",IfNotFound=Warn)
# SetReservoirStation(ID="5903663",AccountID=2,AccountName="F&W",AccountMax=280,AccountInitial=280,AccountEvap=0,AccountOneFill=1,IfNotFound=Warn)
# #  Farris Creek Reservoir
# SetReservoirStation(ID="5903602",Name="Farris Creek Resevoir",RiverNodeID="ID",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=3170,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Irrigation",AccountMax=3000,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10010,100",ContentAreaSeepage="0.00,0.00,0;3000,69,0;9999999,69,0",IfNotFound=Warn)
# #  Rainbow Lake Reservoir
# SetReservoirStation(ID="5903664",Name="Rainbow Lake Reservoir",OnOff=1,OneFillRule=-1,DailyID="5",ContentMin=0,ContentMax=200,ReleaseMax=999999,DeadStorage=0,AccountID=1,AccountName="Irrigation",AccountMax=200,AccountInitial=0,AccountEvap=0,AccountOneFill=1,EvapStations="10006,100",ContentAreaSeepage="0.00,0.00,0;200,15,0;9999999,15,0",IfNotFound=Warn)
# #
# WriteReservoirStationsToStateMod(OutputFile="..\StateMod\gm2015B.res")
# 
# -----------------------------------------------------------------------------
# HydroBase database is: HydroBase_CO_20150304 on Katie
# HydroBase.db_version:  design version: 20141201  last data change: 20150304
# HydroBase table structure for software is at least 2013040420130404
# HydroBase input name is "".
# Stored procedures are being used.
# -----------------------------------------------------------------------------
# 
#------------------------------------------------
#>
#> *************************************************************
#>  StateMod Reservoir Station file
#>
#>  Card 1   format:  (a12, a24, a12, i8, f8.0, 1x, a12)
#>
#>  ID       cresid:  Reservoir Id
#>  Name     resnam:  Reservoir name
#>  Riv ID    cgoto:  Node where Reservoir is located
#>  On/Off   iressw:  Switch 0 = off
#>                           1 = on, do not adjust for dead storage
#>                               do not store above rervoir targets
#>                           2 = do not store above rervoir targets
#>                               adjust maximum ownership and initial
#>                               storage of the last account by the
#>                               dead storage volume
#>                           3 = on, do not adjust for dead storage
#>                               do store above rervoir targets
#>                               (Note: in conjunction with an
#>                               operational release for targets this
#>                               results in a 'paper fill' activity.)
#>  Admin #   rdate:  Administration date for 1 fill rule
#>  Daily ID cresdy:  Identifier for daily time series.
#>
#>  Card 2 format:  (24x, 4f8.0, 4i8)
#>
#>  VolMin   volmin:  Min storage (ac-ft)
#>  VolMax   volmax:  Max storage (ac-ft)
#>  FloMax   flomax:  Max discharge (cfs)
#>  DeadSt   deadst:  Dead storage (ac-ft)
#>  NumOwner nowner:  Number of owners
#>  NumEva   nevapo:  Number of evaporation stations
#>  NumPre   nprecp:  Number of precipitation stations
#>  NumTable nrange:  Number of area capacity values
#>
#>  Card 3 format:  (12x, a12, 3f8.0, i8)
#>
#>  OwnName  ownnam:  Owner name
#>  OwnMax   ownmax:  Maximum storage for that owner (ac-ft)
#>  Sto-1    curown:  Initial storage for that owner (ac-ft)
#>  EvapTyp  pcteva:  Evaporation distribution
#>  FillTyp   n2own:  Ownership type 1=First fill; 2=Second fill
#>
#>  Card 4  format:  (24x, a12, f8.0)
#>
#>  Evap ID  cevar:  Evaporation station
#>  EvapWt  weigev:  Evaporation station weight (%%)
#>
#>  Card 5 format:  (24x, a12, f8.0)
#>
#>  Prec ID   cprer:  Precipitation station
#>  PrecWt   weigpr:  Precipitation station weight (%%)
#>
#>  Card 6 format:  (24x, 3f8.0)
#>
#>  Cont     conten:  Content (ac-ft)
#>  Area    surarea:  Area (ac)
#>  Seep    seepage:  Seepage (ac-ft)
#>
#> *************************************************************
#>
#>    ID              Name              Node     On/Off  RDate       DailyID 
#>---------eb----------------------eb----------eb------eb------exb----------e
#>                       VolMin  VolMax  FloMax  DeadSt NumOwner NumEva  NumPre NumTable
#>xxxxxxxxxxxxxxxxxxxxxxb------eb------eb------eb------eb------eb------eb------eb------e
#>                         OwnName   OwnMax   Sto-1 EvapTyp FillTyp
#>xxxxxxxxxxxxxxxxxxxxxxb----------eb------eb------eb------eb------e
#>                        Evap Id    EvapWt 
#>xxxxxxxxxxxxxxxxxxxxxxb----------eb------e
#>                        Prec Id    PrecWt 
#>xxxxxxxxxxxxxxxxxxxxxxb----------eb------e
#>                        Cont    Area    Seep  
#>xxxxxxxxxxxxxxxxxxxxxxb------eb------eb------e
#>EndHeader
#>
2803590     HOT SPRINGS RES         2803590            1     11. 5           
                              0.    966. 999999.      0.       1       1       0       3
            Acc1            966.    966.       0       1
            Evaporation 10010           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    1029.   41.00       0
            CAP-AREA  2 9999999.   41.00       0
2803591     MCDONOUGH RES FIRST ENLT2803591            1     11. 5           
                              0.   1697. 999999.      0.       1       1       0       3
            Acc1           1697.   1697.       0       1
            Evaporation 10010           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    1808.   72.00       0
            CAP-AREA  2 9999999.   72.00       0
2803592     MCDONOUGH RES NO 2      2803592            1     11. 5           
                              0.   1665. 999999.      0.       1       1       0       3
            Acc1           1665.   1665.       0       1
            Evaporation 10010           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    1774.   71.00       0
            CAP-AREA  2 9999999.   71.00       0
2803593     NEEDLE CREEK RES        2803593            1     11. 5           
                              0.   1218. 999999.      0.       1       1       0       3
            Acc1           1218.   1218.       0       1
            Evaporation 10010           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    1298.   52.00       0
            CAP-AREA  2 9999999.   52.00       0
2803594     UPPER DOME RESERVOIR    2803594            1     11. 5           
                              0.    826. 999999.      0.       1       1       0       3
            Acc1            826.    758.       0       1
            Evaporation 10010           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     880.   35.00       0
            CAP-AREA  2 9999999.   35.00       0
2803595     VOUGA RESERVOIR         2803595            1     11. 5           
                              0.   1361. 999999.      0.       1       1       0       3
            Acc1           1361.   1361.       0       1
            Evaporation 10010           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    1450.   58.00       0
            CAP-AREA  2 9999999.   58.00       0
2803617     LOWER DOME RESERVOIR    2803617            1     11. 5           
                              0.     56. 999999.      0.       1       1       0       3
            Acc1             56.     56.       0       1
            Evaporation 10010           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    60.00    2.00       0
            CAP-AREA  2 9999999.    2.00       0
2803652     BOULDER LAKE            2803652            1     11. 5           
                              0.     97. 999999.      0.       1       1       0       3
            Acc1             97.     97.       0       1
            Evaporation 10010           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     104.    4.00       0
            CAP-AREA  2 9999999.    4.00       0
2803674     PETERSON RESERVOIR      2803674            1     11. 5           
                              0.    178. 999999.      0.       1       1       0       3
            Acc1            178.    178.       0       1
            Evaporation 10010           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     190.    8.00       0
            CAP-AREA  2 9999999.    8.00       0
28_ARG001   AGG_RES_Tomichi         28_ARG001          1     -1. 5           
                              0.    146. 999999.      0.       1       1       0       3
            AGG_RES_Tomi    146.    146.       0       1
            Evaporation 10010           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     156.    6.00       0
            CAP-AREA  2 9999999.    6.00       0
4003365     FRUIT GROWERS RES       4003365            1     -1. 5           
                              0.   4262. 999999.      0.       2       1       0       3
            Irrigation     4186.   4186.       0       1
            Dead_Pool        75.     75.       0       1
            Evaporation 10009           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    4792.     476       0
            CAP-AREA  2 9999999.     476       0
4003395     FRUITLAND RESERVOIR     4003395            1     -1. 5           
                              0.   7604. 999999.      0.       1       1       0       3
            Irrigation     7604.   7604.       0       1
            Evaporation 10009           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    9900.     200       0
            CAP-AREA  2 9999999.     200       0
4003399     OVERLAND RES NO 1       4003399            1     -1. 5           
                              0.   5820. 999999.      0.       2       1       0      11
            Irrigation     5771.   5771.       0       1
            Dead_Pool        48.     48.       0       1
            Evaporation 10010           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    52.00   19.00       0
            CAP-AREA  2     196.   39.00       0
            CAP-AREA  3     483.   76.00       0
            CAP-AREA  4     985.     124       0
            CAP-AREA  5    1699.     161       0
            CAP-AREA  6    2571.     187       0
            CAP-AREA  7    3559.     208       0
            CAP-AREA  8    4645.     226       0
            CAP-AREA  9    5828.     247       0
            CAP-AREA 10 9999999.     247       0
4003416     PAONIA RESERVOIR        4003416            1     -1. 5           
                              0.  17555.   1130.      0.       4       1       0      11
            Fire_Mtn      11875.  11875.       0       1
            Ragged_Mtn     1877.   1877.       0       1
            Endangered_F   1408.   1408.       0       1
            Dead_Pool      2393.   2393.       0       1
            Evaporation 10011           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     184.   23.00       0
            CAP-AREA  2     843.   44.00       0
            CAP-AREA  3    2071.   89.00       0
            CAP-AREA  4    4877.     177       0
            CAP-AREA  5    6896.     227       0
            CAP-AREA  6    9319.     258       0
            CAP-AREA  7   12053.     289       0
            CAP-AREA  8   15052.     311       0
            CAP-AREA  9   20950.     333       0
            CAP-AREA 10 9999999.     333       0
4003527     Gorsuch Reservoir       4003527            1     -1. 5           
                              0.  23469. 999999.      0.       2       1       0       3
            Irrigation    22530.      0.       0       1
            Inactive        938.      0.       0       1
            Evaporation 10009           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1   25000.    2500       0
            CAP-AREA  2 9999999.    2500       0
4003553     CRAWFORD RESERVOIR      4003553            1     -1. 5           
                              0.  13513. 999999.      0.       2       1       0      11
            Irrigation     9716.   9716.       0       1
            Recreation     3797.   3797.       0       1
            Evaporation 10009           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     116.   13.00       0
            CAP-AREA  2     602.   41.00       0
            CAP-AREA  3    1126.   65.00       0
            CAP-AREA  4    1924.   98.00       0
            CAP-AREA  5    3087.     135       0
            CAP-AREA  6    4714.     193       0
            CAP-AREA  7    6926.     251       0
            CAP-AREA  8    9745.     313       0
            CAP-AREA  9   14633.     406       0
            CAP-AREA 10 9999999.     406       0
40_ARG001   AGG_RES_Surface         40_ARG001          1     -1. 5           
                              0.  21843. 999999.      0.       1       1       0       3
            AGG_RES_Surf  21843.  21843.       0       1
            Evaporation 10009           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1   23268.     931       0
            CAP-AREA  2 9999999.     931       0
40_ARG002   AGG_RES_Ngunn           40_ARG002          1     -1. 5           
                              0.  21843. 999999.      0.       1       1       0       3
            AGG_RES_Ngun  21843.  21843.       0       1
            Evaporation 10009           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1   23268.     931       0
            CAP-AREA  2 9999999.     931       0
40_ASG001   AGG_STOCK_Surface       40_ASG001          1     -1. 5           
                              0.   1621. 999999.      0.       1       1       0       3
            AGG_STOCK_Su   1621.   1621.       0       1
            Evaporation 10012           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    1727.     173       0
            CAP-AREA  2 9999999.     173       0
41_ARG001   AGG_RES_Uncomp          41_ARG001          1     -1. 5           
                              0.   3028. 999999.      0.       1       1       0       3
            AGG_RES_Unco   3028.   3028.       0       1
            Evaporation 10012           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    3226.     129       0
            CAP-AREA  2 9999999.     129       0
41_ASG001   AGG_STOCK_Uncomp        41_ASG001          1     -1. 5           
                              0.   1621. 999999.      0.       1       1       0       3
            AGG_STOCK_Un   1621.   1621.       0       1
            Evaporation 10012           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    1727.     173       0
            CAP-AREA  2 9999999.     173       0
41_Cerro    Cerro                   41_Cerro           1     11. 5           
                              0.    610.      2.      0.       1       1       0       3
            Project7        610.    610.       0       1
            Evaporation 10012           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     650.   28.00       0
            CAP-AREA  2 9999999.   28.00       0
41_Fairvw   Fairview                41_Fairvw          1     -1. 5           
                              0.    328. 999999.      0.       1       1       0       3
            Project7        328.    328.       0       1
            Evaporation 10012           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     350.   36.00       0
            CAP-AREA  2  999999.   36.00       0
42_ARG001   AGG_RES_Kannah          42_ARG001          1     -1. 5           
                              0.  16781. 999999.      0.       1       1       0       3
            AGG_RES_Kann  16781.  16781.       0       1
            Evaporation 10012           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1   17876.     715       0
            CAP-AREA  2 9999999.     715       0
42_ASG001   AGG_STOCK_Kannah        42_ASG001          1     -1. 5           
                              0.   1621. 999999.      0.       1       1       0       3
            AGG_STOCK_Ka   1621.   1621.       0       1
            Evaporation 10012           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    1727.     173       0
            CAP-AREA  2 9999999.     173       0
5903602     Farris Creek Resevoir   5903602            1     -1. 5           
                              0.   2975. 999999.      0.       1       1       0       3
            Irrigation     2816.      0.       0       1
            Evaporation 10010           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    3000.   69.00       0
            CAP-AREA  2 9999999.   69.00       0
5903660     Cunningham Gulch        5903660            1     -1. 5           
                              0.     79. 999999.      0.       1       1       0       3
            Irrigation       79.      0.       0       1
            Evaporation 10006           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    85.00   50.00       0
            CAP-AREA  2 9999999.   50.00       0
5903663     Meridian Lake           5903663            1     -1. 5           
                              0.   1295. 999999.      0.       2       1       0       3
            Irrigation     1032.   1032.       0       1
            F&W             262.    262.       0       1
            Evaporation 10006           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    1380.   50.00       0
            CAP-AREA  2 9999999.   50.00       0
5903664     Rainbow Lake Reservoir  5903664            1     -1. 5           
                              0.    187. 999999.      0.       1       1       0       3
            Irrigation      187.      0.       0       1
            Evaporation 10006           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1     200.   15.00       0
            CAP-AREA  2 9999999.   15.00       0
5903666     TAYLOR PARK RESERVOIR   5903666            1     -1. 5           
                              0. 101848.   1500.      0.       3       1       0      11
            UVWUA         99699.  99699.       0       1
            Dead_Pool      2149.   2149.       0       1
            UGRWCD        99699.      0.       0       2
            Evaporation 10010           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1   20000.     639       0
            CAP-AREA  2   30000.     846       0
            CAP-AREA  3   40000.    1061       0
            CAP-AREA  4   50000.    1274       0
            CAP-AREA  5   60000.    1451       0
            CAP-AREA  6   70000.    1603       0
            CAP-AREA  7   80000.    1742       0
            CAP-AREA  8   90000.    1870       0
            CAP-AREA  9  108490.    2060       0
            CAP-AREA 10 9999999.    2060       0
59_ARG001   AGG_RES_East            59_ARG001          1     -1. 5           
                              0.   9224. 999999.      0.       1       1       0       3
            AGG_RES_East   9224.   9224.       0       1
            Evaporation 10006           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    9826.     393       0
            CAP-AREA  2 9999999.     393       0
6203532     BLUE MESA RESERVOIR     6203532            1     -1. 5           
                              0. 883210. 999999.      0.       3       1       0      11
            USA          702710. 702710.       0       1
            Dead_Pool    180500. 180500.       0       1
            UVWUA         99699.      0.       0       2
            Evaporation 10011           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1   10000.     350       0
            CAP-AREA  2   40000.     800       0
            CAP-AREA  3  111200.    1800       0
            CAP-AREA  4  175000.    2300       0
            CAP-AREA  5  220000.    3100       0
            CAP-AREA  6  310000.    4200       0
            CAP-AREA  7  425000.    5400       0
            CAP-AREA  8  570000.    7000       0
            CAP-AREA  9  940800.    9180       0
            CAP-AREA 10 9999999.    9180       0
6203545     MORROW POINT RESERVOIR  6203545            1     11. 5           
                              0. 111494. 999999.      0.       2       1       0      16
            Acc1          39541.  39541.       0       1
            Dead_Pool     71952.  71952.       0       1
            Evaporation 10011           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    5000.     111       0
            CAP-AREA  2   10000.     186       0
            CAP-AREA  3   15000.     222       0
            CAP-AREA  4   20000.     264       0
            CAP-AREA  5   25000.     313       0
            CAP-AREA  6   30000.     352       0
            CAP-AREA  7   40000.     411       0
            CAP-AREA  8   50000.     471       0
            CAP-AREA  9   60000.     531       0
            CAP-AREA 10   70000.     583       0
            CAP-AREA 11   90000.     679       0
            CAP-AREA 12  100000.     727       0
            CAP-AREA 13  110000.     781       0
            CAP-AREA 14  118764.     838       0
            CAP-AREA 15 9999999.     838       0
6203548     SILVERJACK RESERVOIR    6203548            1     -1. 5           
                              0.  12692.    280.      0.       2       1       0      11
            Irrigation    12051.  12051.       0       1
            Dead_Pool       641.    641.       0       1
            Evaporation 10012           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    1200.   62.00       0
            CAP-AREA  2    1930.   83.00       0
            CAP-AREA  3    2870.     107       0
            CAP-AREA  4    4070.     133       0
            CAP-AREA  5    5560.     164       0
            CAP-AREA  6    7350.     195       0
            CAP-AREA  7    9470.     229       0
            CAP-AREA  8   11950.     268       0
            CAP-AREA  9   13900.     293       0
            CAP-AREA 10 9999999.     293       0
6203578     CRYSTAL RESERVOIR       6203578            1     11. 5           
                              0.  23691. 999999.      0.       1       1       0      15
            Acc1          23691.  23691.       0       1
            Evaporation 10011           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    2000.     151       0
            CAP-AREA  2    4000.     172       0
            CAP-AREA  3    6000.     191       0
            CAP-AREA  4    8000.     210       0
            CAP-AREA  5   10000.     229       0
            CAP-AREA  6   12000.     250       0
            CAP-AREA  7   14000.     267       0
            CAP-AREA  8   16000.     287       0
            CAP-AREA  9   18000.     304       0
            CAP-AREA 10   20000.     322       0
            CAP-AREA 11   22000.     336       0
            CAP-AREA 12   24000.     350       0
            CAP-AREA 13   25236.     350       0
            CAP-AREA 14 9999999.     350       0
62_ARG001   AGG_RES_Lake            62_ARG001          1     -1. 5           
                              0.   6078. 999999.      0.       1       1       0       3
            AGG_RES_Lake   6078.   6078.       0       1
            Evaporation 10011           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    6475.     259       0
            CAP-AREA  2 9999999.     259       0
62_ARG002   AGG_RES_Main            62_ARG002          1     -1. 5           
                              0.   6078. 999999.      0.       1       1       0       3
            AGG_RES_Main   6078.   6078.       0       1
            Evaporation 10011           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    6475.     259       0
            CAP-AREA  2 9999999.     259       0
62_ASG001   AGG_STOCK_Main          62_ASG001          1     -1. 5           
                              0.   1621. 999999.      0.       1       1       0       3
            AGG_STOCK_Ma   1621.   1621.       0       1
            Evaporation 10012           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    1727.     173       0
            CAP-AREA  2 9999999.     173       0
6803675     Ridgway                 6803675            1     -1. 5           
                              0.  79296.    500.      0.       6       1       0      12
            Project7      26379.  26379.       0       1
            UVWUA         10514.  10514.       0       1
            Recreation    18024.  18024.       0       1
            Dead_Pool     23532.  23532.       0       1
            Unallocated     844.    844.       0       1
            Exchange      26379.      0.       0       1
            Evaporation 10012           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    1430.   85.00       0
            CAP-AREA  2    4150.     203       0
            CAP-AREA  3    9657.     345       0
            CAP-AREA  4   17637.     457       0
            CAP-AREA  5   27841.     572       0
            CAP-AREA  6   40315.     684       0
            CAP-AREA  7   55382.     815       0
            CAP-AREA  8   73146.     971       0
            CAP-AREA  9   84467.    1063       0
            CAP-AREA 10   85897.    1063       0
            CAP-AREA 11 9999999.    1063       0
68_ARG001   AGG_RES_UpperUncomp     68_ARG001          1     -1. 5           
                              0.   7847. 999999.      0.       1       1       0       3
            AGG_RES_Uppe   7847.   7847.       0       1
            Evaporation 10012           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    8359.     334       0
            CAP-AREA  2 9999999.     334       0
68_ASG001   AGG_STOCK_UpperUncomp   68_ASG001          1     -1. 5           
                              0.   1621. 999999.      0.       1       1       0       3
            AGG_STOCK_Up   1621.   1621.       0       1
            Evaporation 10012           100.
            CAP-AREA  0     0.00    0.00       0
            CAP-AREA  1    1727.     173       0
            CAP-AREA  2 9999999.     173       0
